version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    ports:
      - 27018:27017
    volumes:
      - './backup:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:1234@localhost:27017/
#docker-compose -f mongo-compose.yml up
# --detach : chạy ngầm